// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Opal.Client.Api.Http.V02.Channels;
using Opal.Client.Api.Http.V02.Conversations;
using Opal.Client.Api.Http.V02.Events;
using Opal.Client.Api.Http.V02.Notifications;
using Opal.Client.Api.Http.V02.Users;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Opal.Client.Api.Http.V02
{
    /// <summary>
    /// Builds and executes requests for operations under \api\http\v0.2
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V02RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The channels property</summary>
        public global::Opal.Client.Api.Http.V02.Channels.ChannelsRequestBuilder Channels
        {
            get => new global::Opal.Client.Api.Http.V02.Channels.ChannelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The conversations property</summary>
        public global::Opal.Client.Api.Http.V02.Conversations.ConversationsRequestBuilder Conversations
        {
            get => new global::Opal.Client.Api.Http.V02.Conversations.ConversationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Opal.Client.Api.Http.V02.Events.EventsRequestBuilder Events
        {
            get => new global::Opal.Client.Api.Http.V02.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notifications property</summary>
        public global::Opal.Client.Api.Http.V02.Notifications.NotificationsRequestBuilder Notifications
        {
            get => new global::Opal.Client.Api.Http.V02.Notifications.NotificationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Opal.Client.Api.Http.V02.Users.UsersRequestBuilder Users
        {
            get => new global::Opal.Client.Api.Http.V02.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Opal.Client.Api.Http.V02.V02RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V02RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/http/v0.2", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Opal.Client.Api.Http.V02.V02RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V02RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/http/v0.2", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
