// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Opal.Client.Api.Http.V02;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Opal.Client.Api.Http
{
    /// <summary>
    /// Builds and executes requests for operations under \api\http
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HttpRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The v02 property</summary>
        public global::Opal.Client.Api.Http.V02.V02RequestBuilder V02
        {
            get => new global::Opal.Client.Api.Http.V02.V02RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Opal.Client.Api.Http.HttpRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HttpRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/http", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Opal.Client.Api.Http.HttpRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HttpRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/http", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
