// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Opal.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ChatUserState
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "Disabled")]
        #pragma warning disable CS1591
        Disabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "Banned")]
        #pragma warning disable CS1591
        Banned,
        #pragma warning restore CS1591
        [EnumMember(Value = "Suspended")]
        #pragma warning disable CS1591
        Suspended,
        #pragma warning restore CS1591
    }
}
