// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Opal.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ChatUserType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Constant")]
        #pragma warning disable CS1591
        Constant,
        #pragma warning restore CS1591
        [EnumMember(Value = "Ordinary")]
        #pragma warning disable CS1591
        Ordinary,
        #pragma warning restore CS1591
    }
}
