// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Opal.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EventType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NewConversation")]
        #pragma warning disable CS1591
        NewConversation,
        #pragma warning restore CS1591
        [EnumMember(Value = "LeaveConversation")]
        #pragma warning disable CS1591
        LeaveConversation,
        #pragma warning restore CS1591
        [EnumMember(Value = "NewChannel")]
        #pragma warning disable CS1591
        NewChannel,
        #pragma warning restore CS1591
        [EnumMember(Value = "LevelChannel")]
        #pragma warning disable CS1591
        LevelChannel,
        #pragma warning restore CS1591
        [EnumMember(Value = "Custom")]
        #pragma warning disable CS1591
        Custom,
        #pragma warning restore CS1591
    }
}
